### ISSUE TITLE
Feature request: support organization-level projects

### ISSUE THREAD

**Issue by darrellrossman** [1natsu172/github-action-auto-card-assign#8]
@1natsu172 - this is an excellent GitHub action! Thank you very much for putting it together.

I would like to use this action with projects that are under an organization rather than under a repository. I can look into making this change when I get some free time, but wanted to see if you have any thoughts on such a feature.

Thank you once more!

**Comment by 1natsu172** [comment]
@darrellrossman Hello.

I know that organization have GitHub Projects, but I don't think you can set Github actions directly under an organization. Actions are set in the repository.

As long as Actions is not in the organization, there is nothing we can do about it.

regards.
